# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=100),
        ),
    ]
